#!/bin/sh
echo "Working directory: $1"

find ./constructs/"$1" -type f -name "*.bicep" -print0 | while read -d $'\0' file
do
  echo "$file"
  az bicep build --file "$file" --outdir output --only-show-errors
done
